services:
  - type: web
    name: employee-service
    runtime: node
    buildCommand: cp -r ../proto ./proto && npm install --include=dev && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
